### ISSUE TITLE
Incorporate site data into sites page 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#120]
## Description
Our site page and site cards currently display hardcoded data. We need to have the site page display cards corresponding to all of a user's sites, and we need to have each card display relevant data about its respective site. 

<img width="394" alt="Screen Shot 2023-03-16 at 1 44 00 PM" src="https://user-images.githubusercontent.com/62641231/225721969-d8a175db-a002-49ea-a6fb-99667592e9a6.png">

## Todos

- [x] populate site page with user's site list 
  - it might be beneficial to create a simple hook for the useSWR call for retrieving the site list
- [x] refactor cards to allow UUID to be passed in 
- [x] retrieve relevant data in cards using the `useSiteData` hook
- [x] display relevant data in cards 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=533%3A2251&t=4bIRt8hHMIjG4265-1)

## Time estimate
tbd
