### ISSUE TITLE
Mini graph component for site card

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#124]
## Description

Create a mini graph component, with a gradient starting at the top and ending at the "sunny" threshold. Can consult our ThresholdGraph.

<img width="319" alt="Screen Shot 2023-03-16 at 8 54 45 PM" src="https://user-images.githubusercontent.com/62641231/225792248-ddd92fd9-a7ad-4492-beaa-74b2dc9d7506.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] create mini line graph component 
- [x] create linear gradient to add to mini line graph component 
- [x] add graph component to site cards 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=913%3A2570&t=wcr1jOiRz7h5wkK5-1)
- [recharts areachart](https://recharts.org/en-US/api)
- [recharts tinylinechart example](https://recharts.org/en-US/examples/TinyLineChart)
