### ISSUE TITLE
Clear sky line in graph

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#128]
## Description
Add a blue line to our long-term graph in the dashboard to display the estimated output for a site under a clear sky. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] pull mock data from the `GET /sites/{site_uuid}/clearsky` endpoint [in this PR ](https://github.com/openclimatefix/pv-site-api/pull/53)
- [x] add mock data to our mock API routes 
- [x] fetch data, either through creating a new custom hook, or through adding a call to the clearsky endpoint in the `useSiteData` hook 
- [ ] graph data in our graph 
- [ ] update legend and other graph features accordingly
- [ ] style according to figma 

## Time estimate
tbd!
