### ISSUE TITLE
Display corresponding dashboard pages for each unique site card 

### ISSUE THREAD

**Issue by rohanvan123** [openclimatefix/pv-sites-mobile#137]
## Description
For this feature, our goal is for a user to be able to click on a specific site card and be rerouted to its corresponding Dashboard page with the correct information. Currently, each site card links to the default dashboard page that we have set up. However, we want site cards to link specifically to the right dashboard based on the site's UUID. 

A straightforward approach is to let Next.js file/dynamic routing do most of the work for us, we want to have some type of identifiable key parameter in the link that our site card contains. An example of this would be "/dashboard/{site_uuid}", where using some Next.js library, we can store the site_uuid string and then render our dashboard page based off of it. This would also require modifying the href tag for site card components as they will no longer link to the default dashboard but the new route. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Create some dashboard/[uuid] folder route such that [uuid] can be any string, assuming it is a valid uuid (don't worry about edge cases for now)
- [ ]  Retrieve that specific [uuid] value with the useRouter hook
- [ ] Render a dashboard based on the [uuid] value
- [ ] Alter site card components to link to our new dynamic routes

## Useful links
- [Next.js Dynamic Routes](https://nextjs.org/docs/routing/dynamic-routes)
- [Retrieving current path with Next](https://stackoverflow.com/questions/64836086/accessing-parameter-from-dynamic-route-in-next-js)
