### ISSUE TITLE
Desktop dashboard design implementation 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#138]
## Description
Implement the desktop designs for the dashboard page. 

## Implementation details 
Because SSR doesn't play nice with the JavaScript `Window` interface[^1], we'd like to use CSS media queries to carry out responsiveness. For the modules, we can simply use tailwind breakpoints to modify styling on desktop. 

To use media queries for the overall dashboard layout, it might be very useful to employ [grid template areas](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas). Because tailwind doesn't support grid template areas by default, we'll have to add [this](https://www.npmjs.com/package/@savvywombat/tailwindcss-grid-areas) package, allowing us to use areas with tailwind. 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Use responsive styling to change the appearance of dashboard modules (a decent number will be taken care of just by changing `<NumberDisplay>`)
- [x] Add the [tailwindcss-grid-area](https://www.npmjs.com/package/@savvywombat/tailwindcss-grid-areas)s package to our repository
- [x] Refactor dashboard to utilize grid areas 
- [x] Change ordering/layout of grid areas correspondingly, based on media queries

## Useful links

- [grid template areas mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas)
- [tailwindcss-grid-areas package](https://www.npmjs.com/package/@savvywombat/tailwindcss-grid-areas)
- [figma dashboard designs](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A4286&t=s3eCMMkkT4zH6tdd-1)

## Time estimate
by Monday 3/27

[^1]: window parameters can't be retrieved server-side, which requires us to display some default before window parameters are accessed, which may result in flickering if that default doesn't match the current window size
