### ISSUE TITLE
Change `/dashboard` route to show aggregate data

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#140]
## Description

The `/dashboard` route should be modified to show aggregate data for several of a user's sites. If they only have one site, the user should be redirected to `/dashboard/{site's uuid}`. You can use the [useSiteAggregation](https://github.com/openclimatefix/pv-sites-mobile/blob/4e8eea25f43232c50e1b28fed89570c545b53a5b/lib/hooks/useSiteAggregation.ts#L11) hook to get the aggregate data.

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] In the `/dashboard/` route page (`/dashboard/index.tsx`), handle the case where the user has 1 site in the `withSites()` call. You can see an example of this inside `/index.tsx`. If they have 0 sites, redirect them to `/dashboard/b97f68cd-50e0-49bb-a850-108d4a9f7b7e` (a test site).
- [ ] Change the dashboard modules that make sense to show on the aggregate dashboard to take in as props a _list_ of site UUIDs, rather than just one. (For example, sunny timeframe doesn't make sense since "how long it'll be sunny for" is an almost per-site quality). Update their internal logic to handle this, and their points of consumption.
- [ ] Create a new `Dashboard` component to be the for an aggregate dashboard.

## Useful links

-  [useSiteAggregation](https://github.com/openclimatefix/pv-sites-mobile/blob/4e8eea25f43232c50e1b28fed89570c545b53a5b/lib/hooks/useSiteAggregation.ts#L11)
