### ISSUE TITLE
Display actual site data (hindcast) in graph

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#146]
## Description
Add a line in our graph component to display the actual site data. Also, add a vertical line to denote the current time. 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] add a call to the `pv_actual` endpoint in `useSiteData`
- [x] retrieve `pv_actual` values and add line to graph
- [x] use our `useTime` hook to denote the current time on our graph

## Useful links

-  [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3089&t=5RrD1u05ToevIYkF-1)

## Time estimate
tbd!
