### ISSUE TITLE
Tie threshold graph start and end times to sun event times calculated by Suncalc

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#160]
## Description

The threshold graph's start and end times are currently fixed at 8am and 8pm respectively.
https://github.com/openclimatefix/pv-sites-mobile/blob/afd49547091510610b282d6fb29de62e79ecff34/lib/graphs.ts#L52-L74

These times don't _always_ correspond to starting at 0 solar output and ending at 0, since the season changes the sunrise/sunset times. We should set the start and end time based on the sun rise and sunset time calculated in `useTime`. 
https://github.com/openclimatefix/pv-sites-mobile/blob/afd49547091510610b282d6fb29de62e79ecff34/lib/hooks/useTime.ts#L21-L22

You'll have to expose these times from the hook, and use them to filter the forecast data. Also leave 30 mins of buffer range before and after each event to leave room for output to hit 0. Maybe also round everything to the nearest 30 min interval.

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] Expose the sunrise and sunset times from the hook
- [ ] Leave 30 mins of buffer before the sunrise and 30 mins after the sunset.
- [ ] Round these times off to the nearest 30 min increment that still fits the criterion above
- [ ] Use these times to filter the forecast data ([getClosestForecastIndex](https://github.com/openclimatefix/pv-sites-mobile/blob/afd49547091510610b282d6fb29de62e79ecff34/lib/graphs.ts#L17) may be useful)

## Time estimate

tbd
