### ISSUE TITLE
Site details form for editing sites

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#161]
## Description

Route "edit site" button on cards to form input, and allow site metadata to be edited. We'll need to change the site details page to support a dynamic route `/site-details/[uuid]`, which will give us access to the corresponding (to the UUID) site's data to populate the form.

In addition, populate the context with current site details, specifically the `site_uuid`. Retain site details and populate form inputs/map with current details as defaults. 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Change route structure to support `site-details` for creating a new site and one for editing an existing site.
- [ ] Link existing `edit site` button on Site list page cards to this new route.
- [ ] Fetch site data and populate form fields with the data.
- [ ] Handle submission event, and instead of creating a new site, query the (not yet implemented) API endpoint to edit site data.

## Useful links

- [Next.js dynamic routes](https://nextjs.org/docs/routing/dynamic-routes)

## Time estimate

tbd
