### ISSUE TITLE
Add weather icons to dashboard to show weather at a glance

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#168]
## Description
Add a component to the dashboard to display the weather at a glance 
<img width="415" alt="Screen Shot 2023-03-28 at 1 45 06 AM" src="https://user-images.githubusercontent.com/62641231/228150987-38f8ddb7-377b-4217-9d0f-8b3fd9c4085f.png">

## Implementation Details
We'll be determining which icon to show based on the total expected output over the entire day. This can be calculated using the `getTotalExpectedOutput` function: 
https://github.com/openclimatefix/pv-sites-mobile/blob/27fa0d76aa78b4a649b0dd8873037dd9c1e78637/components/dashboard-modules/ExpectedTotalOutput.tsx#L6-L24
which should probably be refactored into a `utils` file. Furthermore, we'll need to calculate this over each day—we can do this using the `ForecastDataOverDateRange` function: 
https://github.com/openclimatefix/pv-sites-mobile/blob/27fa0d76aa78b4a649b0dd8873037dd9c1e78637/lib/graphs.ts#L39-L49
To find out how "sunny" it'll be, we need to also calculate the total expected output of each day under a clear sky, so we'll have to make sure those functions work with the clearsky estimate, and duplicate+adjust them if they don't. Dividing the forecast expected output and the clearsky expected output should give us a fraction, which we can compare against arbitrary constants to determine which icons are shown. 

## Todos
- [x] calculate output of clear sky day
- [x] scale each day against their respective clear sky days 
- [x] create arbitrary breakpoints to determine which icon must be shown 
- [ ] create/style component according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3089&t=i6hBykmPGHh2S3r1-1)

## Links 
- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3089&t=i6hBykmPGHh2S3r1-1)
