### ISSUE TITLE
Create graph component

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#18]
## Description
Create a preliminary graph component to display forecast

![Screen Shot 2023-02-21 at 12 25 29 PM](https://user-images.githubusercontent.com/62641231/220428540-ac9b0694-1e46-4502-827e-10b0806d62df.png)

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] acquire [forecast data](https://github.com/openclimatefix/pv-sites-mobile/blob/main/data/pv-forecast.json)
- [x] display forecast data using [Recharts](https://recharts.org/en-US/examples)
- [x] style according to designs in [Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=TONZu7WrzKNVaQsB-1)

## Useful links

- [Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=TONZu7WrzKNVaQsB-1)
- [Recharts](https://recharts.org/en-US/examples)
- [forecast data](https://github.com/openclimatefix/pv-sites-mobile/blob/main/data/pv-forecast.json)

## Time estimate
monday 2/27
