### ISSUE TITLE
Protect homepage and form page with auth0

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#19]
## Description

The homepage and form page should be accessible only after logging in, and so must be protected with Auth0's `withPageAuthRequired` function.

This issue also includes some setup for future use of the `pv-site-api` with a user's Auth0 account. Similar to the nowcasting repo, the browser will make requests to the api using the user's auth0 access token. This is fetched from a custom api endpoint like so:

https://github.com/openclimatefix/nowcasting/blob/1d84149c9f4540cc9c314516a259fb4ad540d358/apps/nowcasting-app/pages/api/get_token.ts#L1-L10

Create an endpoint that does exactly this (copy paste...)

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Wrap these pages with Auth0's logic using `getServerSideProps`
- [x] Remove current login button, as this won't be used for now
- [x] Create the `get_token` endpoint

## Useful links

- [withPageAuthRequired docs](https://auth0.github.io/nextjs-auth0/types/helpers_with_page_auth_required.WithPageAuthRequired.html)

## Time estimate

By 2/23
