### ISSUE TITLE
Sites sidebar on desktop 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#196]
## Description

For our desktop views, we're moving different pages to the top navbar, while putting separate sites in the sidebar. This issue will be concerned with refactoring our sidebar to include the site cards. 

Note: implementation of the top navbar isn't covered in this issue, but instead will be addressed in #197.

<img width="203" alt="Screen Shot 2023-04-06 at 2 44 36 PM" src="https://user-images.githubusercontent.com/62641231/230479200-741a03be-b5d2-4aff-b16f-00fdcf360a04.png">

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] refactor sidebar to include sites cards 
- [ ] refactor site cards to include less info 
- [ ] style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3472&t=bsbDamgD9uxuHG4V-1)

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3472&t=bsbDamgD9uxuHG4V-1)

## Time estimate
tbd!
