### ISSUE TITLE
Add sites, pages to top navbar on desktop 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#197]
## Description
For our desktop views, we'd like to move links to different pages (dashboard, more info) to the top navbar, and furthermore, we'd like to include a "sites" button which, on click, will expand a sidebar to display the user's sites. For this issue, we need to add the requisite links and the "sites" button to the top navbar. 

Note: this issue doesn't include implementation of the sites sidebar—that functionality is addressed in #196. 
<img width="720" alt="Screen Shot 2023-04-06 at 2 50 41 PM" src="https://user-images.githubusercontent.com/62641231/230480295-75631100-9e24-4332-923f-fbfd1648a099.png">

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] Add links to top navbar
- [ ] Add sites button to top navbar 
- [ ] Style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3472&t=bsbDamgD9uxuHG4V-1)

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1096%3A3472&t=bsbDamgD9uxuHG4V-1)

## Time estimate
tbd
