### ISSUE TITLE
Implement new site nav profile icon and info dropdown

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#213]
## Description

There were a few changes made to the site nav to make it shorter and include some buttons in its row. Also, a profile picture icon has been added which allows the user to open a dropdown with more account info, and sign out if they'd like to. We need to implement this profile picture icon as a button, with its dropdown.

https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1753-12918&t=fMl5ffH6GbBxNsWT-0

https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1831-12700&t=m77U6aXCdpgLuqRq-0

<img width="364" alt="image" src="https://user-images.githubusercontent.com/23221268/231908973-5a9d8a28-01ff-4aa6-90e2-a65e3b889ea0.png">

<img width="198" alt="image" src="https://user-images.githubusercontent.com/23221268/231911968-4a212919-5c5d-4c8c-9475-17db53cf3f72.png">

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] Add the profile picture icon as a button to the top nav, using the image URL (`picture`) given by the `useUser()` hook from Auth0. 
- [ ] Grab the user's name and email as well to display in the drop.
- [ ] Create a popup next to the button, give it position absolute to appear on top of other stuff

Make sure this works on mobile and desktop

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1753%3A12918&t=fMl5ffH6GbBxNsWT-1)
- [useUser hook](https://auth0.github.io/nextjs-auth0/functions/client_use_user.useUser.html)

## Time estimate
tbd
