### ISSUE TITLE
Create initial inverter linking page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#217]
## Description
Build out a page that links to Enode. 

Should call the proposed `/enode/link` endpoint in the API, which will redirect the user to Enode's Link UI, where they will be able to complete the enode linking process 

![Screen Shot 2023-04-16 at 11 26 25 PM](https://user-images.githubusercontent.com/62641231/232377851-c1a1a57f-72a5-49cf-8ef5-5bb1ca2d8016.png)

<img width="835" alt="Screen Shot 2023-04-17 at 9 06 27 PM" src="https://user-images.githubusercontent.com/62641231/232651320-76765c81-5cb8-4082-a963-cf83597931ee.png">

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] create initial inverter linking page
- [x] build out collapsable "more info" 
- [x] style according to figma, for both [mobile](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=0%3A1&t=ygTyHJgM7GElEArf-1) and [desktop](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=0%3A1&t=ygTyHJgM7GElEArf-1)

## Time estimate
tbd!

**Comment by ericcccsliu** [comment]
Fixed by #231
