### ISSUE TITLE
Build inverter view/select page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#218]
## Description

Build out the page that users will be redirected to after initially linking their inverters with Enode. 
- Because Enode seems to only support linking all inverters of _just one brand_ at a time, we need some functionality to add more inverters from different brands 
- After a user doesn't want to add more inverters, we need to bring them to a page where they may select a subset of inverters which correspond to their site 
- These inverters need to be sent to the API via a `POST`—this hasn't really been planned in the API yet, so hold off on this for now, but make sure that we can easily add the inverters to a `POST` request. 

![Screen Shot 2023-04-16 at 11 30 10 PM](https://user-images.githubusercontent.com/62641231/232378424-e48db613-0c0e-47bc-8b21-81db1617522d.png)
![Screen Shot 2023-04-16 at 11 37 37 PM](https://user-images.githubusercontent.com/62641231/232379375-32cb5f32-e2ea-412b-bf41-7f6bff474201.png)

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Create a selectable card component for individual inverters 
- [x] Create inverter view/select pages 
- [x] Create "add more inverters" button that redirects users back to Enode's Link UI, using the `/enode/link` endpoint 
- [x] Populate inverter cards using API, specifically using the `/inverters` endpoint 
- [x] Store selected inverter UUIDs in context to prepare for `POST`ing

## Time estimate
tbd
