### ISSUE TITLE
Implement static help pages

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#235]
## Description

Create static help pages for when users get lost :(
<img width="513" alt="Screen Shot 2023-04-22 at 10 24 12 PM" src="https://user-images.githubusercontent.com/62641231/233818036-ed5d7c41-b510-4ed8-b07e-fcf4e94698f3.png">
The mobile designs are particularly ambitious, lets implement the desktop designs first and make sure they look reasonable on mobile. 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Install the react-markdown dependency 
- [x] Add content in markdown files 
- [x] Create help page 
- [x] Style content
for styling content: 
- [x] use `components` prop of `<ReactMarkdown>` element to style each heading, subheading, list item, etc 
- [x] add link section to different help subpages on the left 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=2035%3A14075&t=BnHgmOXuaHfDcNkC-1)

**Comment by ericcccsliu** [comment]
note: can build off my current branch `el/help-pages` (you can also rename the branch to your initials), since I already have preliminary content and a very barebones page in there (the content is up! but it is all black so you can't see it against the background unless you highlight lmfao
