### ISSUE TITLE
Add inverter data to `useSiteData` hook

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#238]
## Description

We need to get the inverter data for all the inverters for a site with the `useSiteData` hook. This will use the new endpoint we just created to get the inverter data for a site:

https://github.com/openclimatefix/pv-site-api/blob/9561afc643a1d06fb1a6fac23964d0ae593cbb50/pv_site_api/main.py#L502-L524

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Add a `useSWR` query to get this data from the API
- [x] Perhaps add some TypeScript types to represent this data in the frontend. There may be some almost done examples in the `enode.ts` file.
- [ ] sum up current actual generations from all inverters associated with the site 
- [x] Return the data from the `useSiteData` hook
