### ISSUE TITLE
Add module capacity and inverter capacity to form fields 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#245]
## Description
Title. Also, add these fields in the form context where we handle POSTing to the API

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [ ] Add form fields 
- [ ] Style according to figma
- [ ] Add fields in context 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=1553%3A5061&t=AN9sWviWbWpkn5VE-1)

## Time estimate
<img width="278" alt="Screen Shot 2023-04-24 at 4 52 34 PM" src="https://user-images.githubusercontent.com/62641231/234124756-f51762b4-8fd5-49fc-ac18-e89a37401bec.png">
