### ISSUE TITLE
Implement supported inverter brands on inverter page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#252]
## Description

We'd like to display the icons for all the inverters that are supported by Enode! On mobile, this will look like a lil scrolling section, and on desktop, this will be in a modal. 

<img width="206" alt="Screen Shot 2023-04-26 at 12 01 40 AM" src="https://user-images.githubusercontent.com/62641231/234474202-d8358b4a-71b5-44aa-bd6c-b1bc562323bf.png">
<img width="250" alt="Screen Shot 2023-04-26 at 12 02 00 AM" src="https://user-images.githubusercontent.com/62641231/234474249-22fd8714-cb7a-4dce-81fb-d3dcc68e5cd0.png">
<img width="418" alt="Screen Shot 2023-04-26 at 12 02 17 AM" src="https://user-images.githubusercontent.com/62641231/234474302-310fbda3-e7de-44cc-a3e3-37137b39eb6d.png">

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] grab brand logos—these hopefully are publically available somewhere, @AndrewLester or @ericcccsliu might do this for you
- [x] implement mobile inverter display
- [x] implement desktop inverter display modal 
- [x] put "what's this" display in a modal for mobile 

## Useful links

- y'all know where the figma is by now 

## Time estimate
tbd
