### ISSUE TITLE
Integrate inverter flow with the rest of the app and the API 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#254]
## Description
Connect everything together—add the pages created in #231, #249 to the rest of the site creation flow, connect to the Enode endpoints in the API. 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] Make navigation flow in our app works as intended 
- [x] Connect inverter linking pages to Enode API (follow redirect given by our API) 
- [x] Test POST functionality locally 
- [x] maybe add a mock endpoint for POST as well?

**Comment by ericcccsliu** [comment]
addressed by #260, some more testing required
