### ISSUE TITLE
Small Panel Details Updates

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#27]
## Description

There's been a few small updates to the panel details form to update in the UI. First and foremost, we'll be sticking with a dark mode-first theme from now on. Follow the steps here to enable dark mode for the whole app: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

<img width="222" alt="image" src="https://user-images.githubusercontent.com/23221268/220422814-b99c5cab-ddc1-4eb1-9046-bf844ca2828b.png">

[Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=66%3A881&t=TGzhoeMDJ3N6QHKd-0)

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Toggle dark mode for the whole app
- [ ] Add new input styles
- [ ] Add new text color styles
- [ ] Update background color styles
- [ ] Make sure the page's background color styles are set higher up in the tree (`_app.tsx` potentially)

## Useful links

- [Toggle dark mode](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually)
- `w-full`
- [Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=66%3A881&t=TGzhoeMDJ3N6QHKd-0)

## Time estimate

Thursday Dev night
