### ISSUE TITLE
Navbar and Menu Panel

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#28]
## Description
Create a navbar component that includes the nowcasting logo, an Auth0 profile photo, and a menu icon that opens up a [sidebar](https://www.npmjs.com/package/react-sidebar) component

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] create navbar component 
- [x] add icons/buttons to navbar component
- [x] create sidebar component 
- [x] implement sidebar functionality 
- [x] style according to figma 

## Useful links

- [figma navbar](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=TONZu7WrzKNVaQsB-1)
- [figma menu panel](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=209%3A887&t=TONZu7WrzKNVaQsB-1)
- [react sidebar](https://www.npmjs.com/package/react-sidebar)

## Time estimate
monday 1/27
