### ISSUE TITLE
Small desktop dashboard layout changes

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#295]
## Description
<img width="711" alt="Screenshot 2023-05-12 at 1 53 18 PM" src="https://github.com/openclimatefix/pv-sites-mobile/assets/62641231/8109ceb1-9280-4066-b2b7-84cd98346d6e">
bring everything more in line with our figma! 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] decrease rounding on desktop 
- [x] change font size, weight of headers
- [ ] add headers correspondingly 
- [x] refactor graph to display legend to the side 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/pv-sites-mobile?type=design&node-id=0-1&t=wZHhGKhlTGSY8IGx-0)
