### ISSUE TITLE
Implement Logout Page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#38]
## Description
Implement a logout page where users will be directed after they successfully log out. 

<img width="197" alt="Screen Shot 2023-02-23 at 10 16 59 PM" src="https://user-images.githubusercontent.com/62641231/221090527-49c5d636-b820-4d08-a08d-e1a1fb4e9d02.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] create logout page
- [ ] route logout button in dashboard menu to logout page
- [ ] style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=319%3A893&t=bll5l8FBPzlISlXz-0)

## Useful links
- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=319%3A893&t=bll5l8FBPzlISlXz-0)

## Time estimate
tbd!
