### ISSUE TITLE
Generic Modal + I don't know modal

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#43]
## Description

Clicking the "I don't know" button under Solar panel orientation in the panel details form should popup a modal with some more details. We need a generic modal component to be reused and the content for this specific instance. Along with that, please create a reusable button component.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/23221268/221723418-65b91427-2370-49ab-a0a9-d787e4939224.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Create generic modal component
- [x] Create generic button (from modal button styles)
- [x] Use in specific instance for i don't know button
- [x] Open modal on click

## Useful links

- https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=425%3A2092&t=BV2V0vpvaxOq9A8r-0
- https://github.com/KittyGiraudel/react-a11y-dialog
