### ISSUE TITLE
Current output and current percent yield modules

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#44]
## Description
Create current output and current percent yield modules. For output, look at the forecast that is closest to the current time. For percent yield, use output data as well as `installed_capacity_kw` information from the `sites/site_list` endpoint. 

<img width="325" alt="Screen Shot 2023-02-27 at 7 16 30 PM" src="https://user-images.githubusercontent.com/62641231/221727179-94e78035-f88a-4771-ad20-a46ebf349d85.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] acquire data within each module component using SWR 
- [x] get the closest forecasted `expected_generation_kw` datapoint 
- [x] calculate percent yield 
- [ ] style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=389%3A963&t=yMNRyKNs88okH6Dj-1)

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=389%3A963&t=yMNRyKNs88okH6Dj-1)

next devnight 3/2
