### ISSUE TITLE
Form context and submission to mock endpoint

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#45]
## Description

Add a context provider and hook system to store form data for both form pages, and send all the aggregated data to the right endpoint to save the data for a user. After this data is saved, redirect them to the dashboard (for now).

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Create a context provider/hook system to store and update form data for the location input and panel details pages
- [x] Upon submission on the panel details page, send this data to the api endpoint
- [x] After success, redirect them to the right page

## Useful links

- https://reactjs.org/docs/context.html
- Amit's context presentation
