### ISSUE TITLE
Near future threshold based graph

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#48]
## Description

Create the near future threshold based graph:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/23221268/221758607-fd4eefdb-cc7c-4625-8933-4ab5d23bc628.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Pull from [this mock api endpoint](https://github.com/openclimatefix/pv-sites-mobile/blob/43111b8af516c177e314e9cbe659f2e8dea4bd09/pages/api/%5B...mockApiRoute%5D.ts#L40) using [swr](https://swr.vercel.app/)
- [ ] Create the dashed graph line for the actual data using a [tiny area chart](https://recharts.org/en-US/examples/TinyAreaChart). You can get a gradient effect going from [this example](https://recharts.org/en-US/api) (though you want a reverse of theirs)
- [ ] Add a threshold line to the chart at 0.7 for now.
- [ ] Create a custom chart legend like in the figma. You can use an svg or just divs for the example lines
- [ ] Determine whether solar activity is increasing, and for how long ([RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat)). Make sure the intervals are in sorted order and assume the first data point (chronologically) is now (though it may not be in the future)
- [ ] Create a label for the threshold line (2000 kW in the figma). Write 0.7 for now, since our data is only 0-1.
- [ ] Use the arrow icon from [heroicons](https://heroicons.com/) (copy JSX)
- [ ] Apply the circle with ring at the "now" point in the graph (the start, for now). This may be more difficult to do... consult links

## Useful links

- [Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=fRhtAx2p3F4VCA0m-0)
- [Recharts api docs](https://recharts.org/en-US/api)
- [Existing nowcasting app's chart code](https://github.com/openclimatefix/nowcasting/tree/main/apps/nowcasting-app/components/charts). Look at this code for examples on how to render very intricate charts

## Time estimate

We'll try before MPC.
