### ISSUE TITLE
Setup bit.dev and use the Header component

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#5]
## Description

Setup [bit.dev](https://bit.dev/) in this repository and use the Header component. Read through the [docs](https://bit.dev/docs/) for a general understanding, and use the Header component from this [bit cloud setup](https://bit.cloud/openclimatefix/nowcasting-ui). We'll use this component in a `Layout` component similar to @rohanvan123 's in the [test repo](https://github.com/hack4impact-uiuc/ocf-experiment/blob/main/components/Layout.tsx). Add a Layout component here just like his, following [this issue](https://github.com/hack4impact-uiuc/starter-projects/issues/38).

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Install bit https://bit.dev/docs/getting-started/installing-bit/installing-bit/
- [x] Initialize bit for this existing repo ([docs](https://bit.dev/docs/workspace/creating-workspaces/#initialize-a-workspace-on-an-existing-project?new_existing_project=1))
- [ ] [import](https://bit.dev/reference/reference/cli-reference#import) [nowcasting-ui](https://bit.cloud/openclimatefix/nowcasting-ui) as a dependency: `bit import "openclimatefix.nowcasting-ui/*"`
<img width="486" alt="image" src="https://user-images.githubusercontent.com/23221268/219431512-14c3a895-304e-4e0e-9736-da4d6fb630c3.png">
- Tell everyone to run `bit install`

## Useful links

- https://bit.dev/docs/workspace/creating-workspaces/#initialize-a-workspace-on-an-existing-project?new_existing_project=1
- https://bit.dev/docs/quick-start/basic-react
- https://bit.dev/docs/dependencies/dependency-installation
- Bit cloud for Header component: https://bit.cloud/openclimatefix/nowcasting-ui

## Time estimate 
tbd when assigned!
