### ISSUE TITLE
Add Minimal Progressive Web App (PWA) functionality

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#52]
## Description

We'll need to turn our app into a PWA to give users the option to "install" it as an app. The prerequisite for this is creating a [manifest](https://github.com/vercel/next.js/blob/canary/examples/progressive-web-app/public/manifest.json) file and linking it in our [head](https://github.com/vercel/next.js/blob/canary/examples/progressive-web-app/pages/_app.tsx).

By default, this prompt will appear on the first page the user sees on our site. I think it makes more sense to show the PWA install prompt on the dashboard page; the first page the user sees that they'll come back to every day. To do this, we'll need to catch an event and change the time we present the prompt. A quick guide can be found here: https://web.dev/learn/pwa/installation-prompt/#the-beforeinstallprompt-event

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Add a `manifest.json` file to the public folder and customize it to suit our repo
- [ ] Link to the manifest in the `<head`
- [ ] Handle the before install prompt and only re-prompt it on the dashboard page

## Time estimate

tbd
