### ISSUE TITLE
Bottom navbar for mobile

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#55]
## Description
For mobile devices, we'd like to display a bottom navbar rather than our current top navbar. 
![Screen Shot 2023-03-02 at 10 00 28 AM](https://user-images.githubusercontent.com/62641231/222482518-2946ad89-545c-459b-ae14-8ff01ce23f47.png)

## Todos

- [x] create bottom navbar component 
- [x] add bottom navbar to our Layout component 
- [x] conditionally display bottom navbar/top navbar based on device screen size 
- [x] style according to figma

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=506%3A2174&t=ZRBe8mvN0o4UIVXA-1)
- [tailwind docs on responsive design!](https://tailwindcss.com/docs/responsive-design)

## Time estimate
Monday - Thursday
