### ISSUE TITLE
Site card for site page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#59]
## Description
Create a clickable card component to display a site and allow users to navigate to the site's corresponding dashboard. 

## Todos

- [x] create card component 
- [ ] incorporate name/site details from mock data
- [x] link to dashboard page for now 
- [x] style according to figma 

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=533%3A2251&t=BOabqynguS20dI9v-1)

## Time estimate
tbd
