### ISSUE TITLE
Setup Auth0

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#6]
## Description

Setup Auth0 with our app.

## Learning objectives

- Authentication
- Auth0
- Next.js rendering patterns

## Todo

- [x] Obtain the necessary environment variables and store them in a .env
- [x] Follow the Auth0 tutorial to install any packages and setup any routes/pages
- [x] Create signin/signout buttons on the homepage only (put these above the form). Only show signin if signed out, and only show signout if signed in. They can be minimally styled.

## Useful links

- [Auth0 Next.js tutorial](https://auth0.com/docs/quickstart/webapp/nextjs/interactive)

## Time estimate
tbd when assigned!
