### ISSUE TITLE
Power requirement infographic card 

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#66]
## Description
Create an infographic card component to display the power requirements for common household appliances. This component should be a carousel and should support swiping left and right on mobile. To keep track of all of these appliances and their respective power consumption, we'll store some common items in a well-formatted JSON file in the repo to read from and list out in the UI.
<img width="258" alt="Screen Shot 2023-03-05 at 10 36 19 AM" src="https://user-images.githubusercontent.com/62641231/222973455-d6309781-8c62-4577-b9ba-edc9e7c9d39d.png">

also create a more info page to put the card on.
<img width="183" alt="Screen Shot 2023-03-05 at 11 56 14 PM" src="https://user-images.githubusercontent.com/62641231/223030228-85863961-8d25-4d94-bc28-1b17a4b24bcf.png">

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] create card component 
- [x] create more info page
- [x] put card component on more info page
- [x] implement carousel functionality on card component 
- [x] Add carousel elements from the JSON
- [x] [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=506%3A2324&t=XV8OnsZTQVLMrV6i-1)

## Useful links

- [css-tricks css-only carousel guide](https://css-tricks.com/css-only-carousel/) (only consult this if we don't want wrap functionality)
- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=506%3A2324&t=XV8OnsZTQVLMrV6i-1)
