### ISSUE TITLE
Integrate graphs with API deployment

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#67]
## Description
We'd like to start integrating our app with the API deployment. Currently, the API returns a forecast for the next three days, which is a much longer time period than we want for our near-term graph. We'll need to write a helper function to return a portion of this data over a shorter time period, and use that function to feed shorter-term data into our graphs. 

For the near-term graph, we can probably just display the forecast for the current day. @AndrewLester and I were thinking that we could end this graph at 8 pm or so and start displaying the next day's forecast after then. For the longer-term graph further down in the dashboard, we could maybe display the forecast for the next 48 hours, or maybe even just include all the data that the API gives us. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] create separate utils file just for graphs, reorganize current utils file 
- [x] create a helper function to return a subset of API forecast data over a specified time range 
- [x] restrict time ranges displayed in both of our graphs using this helper function 
- [x] reorganize graphs into own directory
- [x] also put an example forecast from the API into our mock data for testing purposes—there might be cases where we still go back to our mock routes, as we might not want to POST to the API for now 

## Useful links

- [api docs](http://pvsite-development-api-sites.eu-west-1.elasticbeanstalk.com/docs)
- [currently working sites](https://www.notion.so/h4iuiuc/pv-sites-api-notes-c3cdacf844d3476c992272cc8b4ef5c2)

## Time estimate
tbd
