### ISSUE TITLE
Create location input component

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#7]
## Description

To allow users to input their precise location, we will use a combination of Mapbox's [GeolocateControl](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/), [Draggable Marker](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/), and [Geocoder Input](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/). Users should be able to: 
- Locate their exact location and then specify the exact location of their solar panels by dragging a marker 
- Enter an address and then specify the exact location of their solar panels by dragging a marker
- Simply drag/zoom the map and then specify the exact location of their solar panels by dragging a marker

Mapbox is very versatile, and our solution should be iterated upon to find the best fit. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] acquire mapbox access token (we should be able to use free tier for now) 
- [x] create map component 
- [ ] implement geocoding input 
- [x] implement placable marker 
- [ ] ensure mobile-friendliness 
- [ ] style according to designs (future task—may still be blocked upon completion of all tasks above)

## Useful links

- [tutorial for mapbox with react](https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/)
- [geocoder with coordinates!](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/)
- [draggable marker](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/)
- [locate user](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/)

## Time estimate
~ 2 weeks
