### ISSUE TITLE
Add zoom-into satellite view on the location input map

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#73]
## Description

We want to let users see their home/roof when selecting the location of solar panels. Mapbox supports "zoom-into satellite" view, where satellite view fades in once zoomed in enough. Follow the tutorial here to implement this (it's a map style change, not code): https://dataplusscience.com/MapboxZoomwithSatellite.html

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Create mapbox account + create new style based on [dark styles](https://studio.mapbox.com/styles/mapbox/dark-v10/)
- [ ] Follow component section of this tutorial: https://dataplusscience.com/MapboxZoomwithSatellite.html
- [ ] Follow the steps at the bottom to get a share link for your custom map styles. Change the name of the theme used in the code to the link

## Useful links

- [Existing dark theme](https://studio.mapbox.com/styles/mapbox/dark-v10/)
- [Satellite zoom tutorial](https://dataplusscience.com/MapboxZoomwithSatellite.html)
