### ISSUE TITLE
Handle form submission loading state in UI

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#76]
## Description

When the panel details form's next button is clicked, which submits the entire user onboarding form, we want to show a loading spinner in the button's text, along with graying the button, to indicate that the form is submitting. We want to wait to redirect the user to the dashboard until after the form is submitted too.

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] Pull the loading indicator from [Chakra UI's spinner](https://chakra-ui.com/docs/components/spinner#usage)
- [x] Make sure the call to the form context's submission (it starts with `set..`) is async, and await it inside your component. Include a local state to denote loading and done loading.
- [x] Redirect user to /dashboard when submitted

## Useful links

- [Chakra UI's spinner](https://chakra-ui.com/docs/components/spinner#usage) inspect element and swipe it
- [CSS animations](https://css-tricks.com/almanac/properties/a/animation/)
