### ISSUE TITLE
Power requirement dashboard module

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#87]
## Description
Create a module on our dashboard that displays common appliances that a user may utilize solely using the current forecasted output of their solar panels. 

<img width="194" alt="Screen Shot 2023-03-07 at 12 21 28 AM" src="https://user-images.githubusercontent.com/62641231/223337575-fa0d1143-7b2e-486a-9038-3c223d1e045a.png">

Consider storing the content to be displayed in a JSON file, similar to issue #66. Consult @anyaparekh on how this should be done. Ideally, the same JSON file would be used to store content for both this issue and #66. 

## Todos
- [x] create module
- [x] add relevant content to JSON file 
- [x] display relevant content based on current predicted output
- [x] style according to figma 
- [x] place onto dashboard page 

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=egs2SijR0fLl8xgd-1)

## Time estimate
tbd!
