### ISSUE TITLE
Sunny timeframe module

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#88]
## Description
create a module that tells our users how long it'll be sunny for! 🌤️ 

<img width="207" alt="Screen Shot 2023-03-07 at 12 33 03 AM" src="https://user-images.githubusercontent.com/62641231/223340221-96f2c130-d74a-4b37-b6f9-d499510a099f.png">

this should work off of the same threshold as our `ThresholdGraph` component. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] write helper function to determine how long we are above the threshold for in our forecast 
- [ ] display that data in module 
- [x] style according to figma 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=egs2SijR0fLl8xgd-1)

## Time estimate
tbd!
