### ISSUE TITLE
Create solar panel parameter input page

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#9]
## Description

Build out the page for inputting solar panel parameters. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] create input field components  
- [x] put together form page
- [x] style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=66%3A881&t=VbR70BBkmE7bxXsb-1) (colors will likely change w/design iteration!)
- [ ] [Required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) - use this appropriately

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=66%3A881&t=VbR70BBkmE7bxXsb-1)

## Screenshots
<img width="258" alt="Screen Shot 2023-02-16 at 1 39 52 PM" src="https://user-images.githubusercontent.com/62641231/219469733-a1add6e0-2023-44d8-a218-0fab55e341ba.png">

## Time estimate
tbd when assigned!
