### ISSUE TITLE
Calculate expected total output

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#91]
## Description
Calculate expected total output using midpoint Riemann sums over the forecasted data. Use this expected total output to create a expected total output module in our dashboard. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] write utils function to calculate expected total output 
- [x] use to create expected total output module in dashboard 
- [x] style according to [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=YXH7cHSbVqUTJzE8-1)

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=188%3A1116&t=YXH7cHSbVqUTJzE8-1)

## Time estimate
before monday 03/20
