### ISSUE TITLE
Extract time-related logic into custom hook

### ISSUE THREAD

**Issue by ericcccsliu** [openclimatefix/pv-sites-mobile#97]
## Description
Currently, we're synchronizing our threshold graph as well as some of our other dashboard modules with the current time. In the threshold graph, we have the following code: 

https://github.com/openclimatefix/pv-sites-mobile/blob/8fa566ef109b31145439fda3ac634f49ef7ce0c9/components/graphs/ThresholdGraph.tsx#L31-L40

We'd like to extract this into a custom hook, perhaps called `useTime` or something similar. Additionally, we'd like to refactor all other instances of utilizing the current time to use our new `useTime` hook. 

Furthermore, in the future, some of our modules will benefit from knowing whether it is day or night, in order to be able to display the most relevant information at all times. To this end, we should be able to use the [SunCalc](https://www.npmjs.com/package/suncalc) library, in conjunction with our users' latitude and longitude, to get times for sunrise and sunset (and dusk, dawn, etc...). We'd like to use the SunCalc library to add a `isNighttime` state to our custom hook, so we may inform modules when it is nighttime and have them update accordingly. 

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [x] refactor interval logic into a custom hook. **Consider:** Should the custom hook do formatting internally, or should that be left up to _consumers_ of the hook?
- [x] refactor files relying on current time to use the current time returned by our custom hook 
- [x] use the SunCalc library to determine whether it is day or night 
- [x] add a state to our time hook to allow components to find out whether it is day or night 

## Useful links

- [intro to react custom hooks](https://beta.reactjs.org/learn/reusing-logic-with-custom-hooks)
- [suncalc](https://www.npmjs.com/package/suncalc)

## Time estimate
tbd!
