### ISSUE TITLE
Location input page desktop design changes

### ISSUE THREAD

**Issue by AndrewLester** [openclimatefix/pv-sites-mobile#99]
## Description

The desktop designs for the location input page have recently changed, and we need to independently make the form look different on desktop than on mobile.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/23221268/224446922-d5ec4d37-f7dc-4c82-862a-e249c5559eab.png">

[Figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=0%3A1&t=MB65jb5aQPcvqULY-0)

## Todos

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- [ ] Since the desktop and mobile designs look so different, for now render a different component on desktop to avoid messing with the correct mobile HTML/tailwind. Detect mobile/desktop with `sm:block hidden`, for example, which will only display on desktop. Use the Tailwind SM breakpoint (or whatever the breakpoint for bottom nav is) for any media query, though you might want to wrap the current mobile stuff in the opposite (`sm:hidden block`). You may be able to reuse parts of the [`LocationInput`](https://github.com/openclimatefix/pv-sites-mobile/blob/main/components/LocationInput.tsx) mapbox code, so try to extract parts of it into a reusable point.
- [ ] Setup first screen with search bar
- [ ] Setup searchbar using mapbox geocoder. If there's no search, the "suggested location" should say "Current Location" and clicking it should [trigger find my location](https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol#trigger). [Geocoder docs](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/) - [more Geocoder docs](https://github.com/mapbox/mapbox-gl-geocoder/blob/main/API.md#mapboxgeocoder).
- [ ] Searching should put marker on map and zoom in.
- [x] Dragging the map moves the marker (or keeps the marker in the center of the screen, if you will). This is current behavior. You'll need to then use reverse geocoding to lookup the lat, lng of the marker's position to change the text in the search, now pinpointed location, bar. See links. Clicking the pinpointed location bar in this stage goes back to the search stage, and focuses the input.
- [ ] Clicking "Confirm", moves to the next page
- [ ] Clicking the usual "find my location" button should also make the marker appear at that location.

## Useful links

- [Designs](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/Wireframes?node-id=0%3A1&t=MB65jb5aQPcvqULY-0)
- https://github.com/mapbox/mapbox-gl-geocoder/blob/main/API.md#transformfeaturetogeolocationtext - could be useful
- [reverse geocoding](https://docs.mapbox.com/api/search/geocoding/#reverse-geocoding)

## Time estimate
tbd

**Comment by ericcccsliu** [comment]
@ashayp22 if you aren't doing this already, using mapbox's [popup](https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup) might be useful for the tooltip that tells a user to drag the map
